### ISSUE TITLE
How is local state access restricted for a yet-to-be-activated?

### ISSUE THREAD

**Issue by ericfs** [KenjiBaheux/portals#10]
Split from https://github.com/KenjiBaheux/portals/issues/9#issuecomment-398407975

Presumably access restriction will require a Feature Policy like for allow-network-access-upon-activation?
Would attempts to access cookies, localStorage, etc. be an error? Even in restricted mode there is the possibility of "scripts that the source trusts via CSP". What will these scripts be allowed to do?

Similar to network requests in #9, I think there is an argument for transparently delaying access so that a developer can avoid lifecycle management, if they don't need it.

**Comment by ericfs** [comment]
Also, from https://github.com/KenjiBaheux/portals/issues/3#issuecomment-398278494, it sounds like there is no way to know that a doc would know it's in yet-to-be-activated mode? If that's the case, then it seems like it would be a problem that it wouldn't know that it shouldn't try to access local state.

**Comment by KenjiBaheux** [comment]
> Even in restricted mode there is the possibility of "scripts that the source trusts via CSP". What will these scripts be allowed to do?

Naively, I'm thinking "anything". 


> "Similar to network requests in #9, I think there is an argument for transparently delaying access so that a developer can avoid lifecycle management, if they don't need it."

I'm not sure that this is an actual concern.
IIRC, there are only 2 modes:
 1. No JS (with perhaps exception for JS served by trusted origins) & No storage access
 2. JS & Storage access under an opaque origin.

In case nb 1, storage access would only be allowed for trusted JS and would not be restricted.
In case nb 2, storage access should "just" work but under an opaque origin.

Am I missing something?

**Comment by ericfs** [comment]
Sorry, I'm confused, you're saying case 1 with trusted origin JS is allowed full access to storage? I was assuming that access to local storage in this case would be an error. If it's not an error, then I agree the point about delayed access is not an actual concern.

**Comment by KenjiBaheux** [comment]
Yes, unless I'm missing a major downside, a trusted origin JS should be allowed full access to storage.
