### ISSUE TITLE
What to call the document that created a now activated portal?

### ISSUE THREAD

**Issue by RByers** [KenjiBaheux/portals#12]
The document that creates a portal is that portal's "embedder". But once the portal is activated, that document may still be relevant (eg. for handling overscroll or other communication as in the case of the top stories carousel). I think we need a term for it. 

I've sometimes used "the portal's referrer" but that's overloaded.

Other ideas? 
/cc @cramforce

**Comment by jeremyroman** [comment]
I've been using the term "predecessor" (e.g. in the name I suggested for putting it in a `<portal>`, `adoptPredecessor`).

**Comment by KenjiBaheux** [comment]
Alternative: "initiator",  the initiator document?

**Comment by probablyup** [comment]
>  But once the portal is activated, that document may still be relevant (eg. for handling overscroll or other communication as in the case of the top stories carousel)

Once the portal is activated, the previous page ceases to exist though right? So in effect there is nothing left to do there and no reason to keep the previous page around.

**Comment by jeremyroman** [comment]
> Once the portal is activated, the previous page ceases to exist though right? So in effect there is nothing left to do there and no reason to keep the previous page around.

We anticipate giving the activated page the opportunity to hold the predecessor alive in a <portal> of its own, to allow smoothly transitioning back to it. For example, a news reader app might allow articles to activate but provide a mechanism for the article to return the user to the news reader or take them to the next article relevant to the user via the news reader.

**Comment by KenjiBaheux** [comment]
Let's go with predecessor for now.
