### ISSUE TITLE
Isn't embedding complete sites as hrefs overkill, instead of a low-cost img and a link tag?

### ISSUE THREAD

**Issue by necccc** [KenjiBaheux/portals#16]
The basic use-case you show in the images is basically a complete product page embedded and preloaded in the site instead of an image and a link. Is this really necessary?

Sorry if this sounds just blatantly negative, I just trying to imagine use cases, where someone would use this, instead of using simpler and cost-effective ways in terms of bandwidth.

**Comment by KenjiBaheux** [comment]
The mocks are a bit simplistic.
As leocavalcante said, it's one possibility.

Portals enables more engaging user experiences than a link+image+snippet can deliver:
 - embedded rich user experience (interactive embeds)
 - fast/instant page loads
 - seamless transitions
 - composed user experience
 - collaborative user experience between embedder and embedded, etc.
