### ISSUE TITLE
Show how to send a message while activating a portal

### ISSUE THREAD

**Issue by jyasskin** [KenjiBaheux/portals#4]
The [example](https://github.com/KenjiBaheux/portals/blob/master/explainer.md#getting-started--example-code) has:

```javascript
insetPortal.activate();
insetPortal.postMessage();
```

But this isn't guaranteed to work, since `.activate()` is a navigation that can kill off the parent page. The opposite:

```javascript
insetPortal.postMessage(...);
insetPortal.activate();
```

is also not guaranteed to work, particularly in the case of [restricted mode](https://github.com/KenjiBaheux/portals/blob/master/explainer.md#constraint-2), where the target can't run Javascript.

I suspect we actually want `.activate()` to accept a message to send to the portal:

```javascript
insetPortal.activate(...);
```

**Comment by jeremyroman** [comment]
For the former, it seems like we could resolve that by making the activation actually happen in a separate task or similar. Avoiding more cases of unloading the document while script is executing it seems desirable.

For the latter...it seems like it depends on the exact semantics we end up with for restrictions. (It's not clear to me whether changing the policy on activation is the only reasonable answer.) If so, that sounds reasonable, except that I'd probably shove it in a dictionary to leave us room for other kinds of options to `activate`. Something like:

```
dictionary PortalActivateOptions {
  optional any data;
}
```

**Comment by KenjiBaheux** [comment]
This definitely seems more robust.
I've added both of you as collaborators, feel free to send a PR or wait until we experiment a bit more.
